### ISSUE TITLE
Go to declaration

### ISSUE THREAD

**Issue by AviFix** [manifestinteractive/android-studio-filetypes#3]
Hi

The 'go to declaration'  dosn't seam to work work js.

Thank's
Avi

**Comment by Ayoitswiz** [comment]
Hello, I did exactly what was said in the directions, my .js files still aren't colored. It didn't change at all. However, the color did change for css, albeit very slightly, still enough.  Thanks for that, but the .js color coding was what I was really after. It's missing all the yellows, and purples like the image below. Please let me know if I might've done something wrong or if you need more info from my situation.

![AnroidStudio-Intellij-Color-Difference](https://user-images.githubusercontent.com/54649757/71682635-4ff73c00-2d5e-11ea-85c5-8c7276f318eb.PNG)

**Comment by manifestinteractive** [comment]
This project is about six years old, and has not been updated since then.  It was initially for the older version of Android Studio, so I doubt this will even work as intended anymore.  Going to archive this repo and update the README to let people know it is no longer being maintained.
